name: Build and Deploy OpenSSL Artifacts

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 2 * * 0" # Weekly rebuild

env:
    CONAN_VERSION: "2.21.0"
    CLOUDSMITH_REPO: "sparesparrow-conan/openssl-artifacts"

jobs:
    build-matrix:
        strategy:
            matrix:
                include:
                    - os: ubuntu-22.04
                      profile: linux-gcc11-fips
                      arch: x86_64
                    - os: ubuntu-22.04
                      profile: linux-arm64-gcc
                      arch: armv8
                    - os: windows-2022
                      profile: windows-msvc193
                      arch: x86_64
                    - os: macos-13
                      profile: macos-arm64
                      arch: arm64

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Setup Conan
              run: |
                  pip install conan==${{ env.CONAN_VERSION }}
                  conan profile detect

            - name: Install openssl-tools
              run: |
                  git clone https://github.com/sparesparrow/openssl-tools.git
                  cd openssl-tools
                  conan export . openssl-tools/1.2.0@
                  conan config install . -sf extensions -tf extensions

            - name: Build with full_deploy
              run: |
                  conan install . \
                    --requires="openssl/3.6.0" \
                    --profile:all=profiles/${{ matrix.profile }} \
                    --build=missing \
                    --deployer=full_deploy_enhanced \
                    --deployer-folder=./deploy

            - name: Create artifact bundle
              run: |
                  cd deploy
                  zip -r ../openssl-${{ matrix.profile }}-${{ matrix.arch }}.zip \
                    full_deploy/ sbom.json fips/

            - name: Upload to Cloudsmith
              if: github.ref == 'refs/heads/main'
              env:
                  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
              run: |
                  pip install cloudsmith-cli
                  cloudsmith push raw ${{ env.CLOUDSMITH_REPO }} \
                    openssl-${{ matrix.profile }}-${{ matrix.arch }}.zip \
                    --version="3.6.0" \
                    --tags="profile:${{ matrix.profile }},arch:${{ matrix.arch }}"

            - name: SBOM Security Scan
              uses: anchore/sbom-action@v0
              with:
                  path: deploy/sbom.json
                  format: cyclonedx-json

